### ISSUE TITLE
naming convention changed for filters

### ISSUE THREAD

**Issue by lenimitoundie** [TAMS-Group/tams_turtlebot#3]
filter type must have specific form of <package_name>/<filter_name>

**Comment by v4hn** [comment]
@lenimitoundie Sorry, I was on leave for two month and just read your issue.
You are right, this is a small issue in [laser_filters.yaml](https://github.com/TAMS-Group/tams_turtlebot/blob/master/tams_turtlebot_bringup/config/laser_filters.yaml).

Are you (still) willing to write a patch for this?

**Comment by lianghongzhuo** [comment]
Did not see this issues before I patch this, cbb39e635a28c2cbd6e0cb957a60c2a25dfab42b
Closed
